[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"
