[build]
  command = "npm run build"
  publish = "build"

# Enable built-in image optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Image processing options
[build.processing.images]
  compress = true