[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"

# Enable built-in image optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Image processing options
[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200